### PR TITLE
chore: 🤖 remove redundant code

### PR DESCRIPTION
**Pull request by IWANABETHATGUY**
Did some refactor, will not merge until the owner did some test refactor @zhusjfaker

### CODE REVIEW

**Review by zhusjfaker — APPROVED** [review]

**Comment by zhusjfaker** [comment]
那个分支。。。其他不太对。。

**Comment by zhusjfaker** [comment]
@IWANABETHATGUY  Sorry, the latest code has just been merged into the main branch. There may be differences and changed codes

**Comment by IWANABETHATGUY** [comment]
Did you pass all tests on your computer ?

**Comment by IWANABETHATGUY** [comment]
image
image
test test::arco_pro::test_arco_pro_42_less ... FAILED
test test::modules::test_less_css_module_render ... FAILED

**Comment by zhusjfaker** [comment]
> > @IWANABETHATGUY Sorry, the latest code has just been merged into the main branch. There may be differences and changed codes
> 
> That's alright, I will open another issue, I found there still some tests did not pass ?


Most of the time to support



CSS module (partially completed)



CSS URL resource extraction



css autoperfix



I haven't had time to support



less mixins

**Pull request closed without merging**
